### ISSUE TITLE
File is missing 

### ISSUE THREAD

**Issue by SHIVAA17** [Haripandey21/Blood_Supply-Dapp#1]
application.css file in not present instylesheets

**Comment by Haripandey21** [comment]
hey @SHIVAA17 , 
It's possible you might encounter this error:
![image](https://github.com/Haripandey21/Blood_Supply-Dapp/assets/69706767/4cc74495-8b4a-43fe-8889-f236d45b9fda)


This error is likely a result of an issue within the assets pipeline. To resolve this, follow these steps:

Run the command rake assets:clobber to clear the assets pipeline.
Compile the pipeline anew by executing rake assets:precompile.
Start the server using bin/dev and halt the server with Ctrl + C.
Launch the server with rails s.
If the error persists, try refreshing the browser tab using Ctrl + R.

Alternatively, you can refer to this instructional video:
https://drive.google.com/file/d/1fVSMNN4Kcv3elQGH9R_g-HQx5gadAI9b/view?usp=drivesdk

**Comment by Haripandey21** [comment]
If you encounter any further problems or have additional questions, please feel free to reopen the issue or create a new one. I'm here to help !!

**Comment by SHIVAA17** [comment]
Extremely sorry for the late response.The instructional video link is not  valid and by following second step " rake assets:precompile".it is creating a lot of issues.
